# AIS python 3.9.1:
# --------------
./build-package.sh -a arm -I leptonica && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I sox && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libwebp && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libacl && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I postgresql && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I attr  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I autoconf  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I bash  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I binutils  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I busybox  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I c-ares  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I ca-certificates  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I command-not-found  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libllvm  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libbz2  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libcurl  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libassuan  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libgcrypt  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I gnupg  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I htop-legacy  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libmosquitto  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I liblzma  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I zlib  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I coreutils  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I dash  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I diffutils  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I dos2unix  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I dpkg  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I ed  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I ffmpeg  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I figlet  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I findutils  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I fontconfig  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I freetype  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I fribidi  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I gawk  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I gdbm  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I git  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I glib  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I grep  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I gzip  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I harfbuzz  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I inetutils  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I json-c  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I krb5  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I ldns  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I less  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libandroid-glob  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libandroid-support  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libass  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libc++  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libcap  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libcrypt  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libdb  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libedit  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libffi  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libfuse  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libgmp  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libgnutls  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libgpg-error  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libgraphite  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libiconv  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libicu  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libidn2  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libjpeg-turbo  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I liblzo  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libmosquitto  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libmp3lame  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libmpfr  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libnettle  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libnghttp2  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libogg  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libopus  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libpng  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libpsl  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libsigsegv  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libsodium  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libsoxr  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libsqlite  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libunistring  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libuuid  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libuv  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libvorbis  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libvpx  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libwebsockets  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libx264  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libx265  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libxml2  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libxslt  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I libzmq  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I m4  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I make  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I nano  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I ncurses  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I ncurses-ui-libs  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I ndk-sysroot  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I net-tools  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I nodejs-lts  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I openssh  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I openssl  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I patch  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I pcre  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I pcre2  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I perl  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I pkg-config  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I procps  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I psmisc  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I python  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I rclone  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I readline  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I sed  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I tar  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I termux-am  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I termux-api  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I termux-auth  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I termux-exec  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I termux-licenses  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I termux-tools  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I ttyd  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I unzip  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I xvidcore  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
./build-package.sh -a arm -I util-linux  && echo SUCCESS >> status.txt || echo FAIL >> status.txt
