# AIS python 3.9.1:
# --------------
./build-package.sh -a arm -I libwebp && echo SUCCESS >> status.txt || echo FAILlibwebp >> status.txt
./build-package.sh -a arm -I libacl && echo SUCCESS >> status.txt || echo FAILlibacl >> status.txt
./build-package.sh -a arm -I attr  && echo SUCCESS >> status.txt || echo FAILattr >> status.txt
./build-package.sh -a arm -I autoconf  && echo SUCCESS >> status.txt || echo FAILautoconf >> status.txt
./build-package.sh -a arm -I bash  && echo SUCCESS >> status.txt || echo FAILbash >> status.txt
./build-package.sh -a arm -I binutils  && echo SUCCESS >> status.txt || echo FAILbinutils >> status.txt
./build-package.sh -a arm -I busybox  && echo SUCCESS >> status.txt || echo FAILbusybox >> status.txt
./build-package.sh -a arm -I c-ares  && echo SUCCESS >> status.txt || echo FAILc-ares >> status.txt
./build-package.sh -a arm -I ca-certificates  && echo SUCCESS >> status.txt || echo FAILca-certificates >> status.txt
./build-package.sh -a arm -I command-not-found  && echo SUCCESS >> status.txt || echo FAILcommand-not-found >> status.txt
./build-package.sh -a arm -I libllvm  && echo SUCCESS >> status.txt || echo FAILlibllvm >> status.txt
./build-package.sh -a arm -I libbz2  && echo SUCCESS >> status.txt || echo FAILlibbz2 >> status.txt
./build-package.sh -a arm -I libcurl  && echo SUCCESS >> status.txt || echo FAILlibcurl >> status.txt
./build-package.sh -a arm -I libassuan  && echo SUCCESS >> status.txt || echo FAILlibassuan >> status.txt
./build-package.sh -a arm -I libgcrypt  && echo SUCCESS >> status.txt || echo FAILlibgcrypt >> status.txt
./build-package.sh -a arm -I gnupg  && echo SUCCESS >> status.txt || echo FAILgnupg >> status.txt
./build-package.sh -a arm -I htop-legacy  && echo SUCCESS >> status.txt ||htop echo FAIL >> status.txt
./build-package.sh -a arm -I libmosquitto  && echo SUCCESS >> status.txt || echo FAILlibmosquitto >> status.txt
./build-package.sh -a arm -I liblzma  && echo SUCCESS >> status.txt || echo FAILliblzma >> status.txt
./build-package.sh -a arm -I zlib  && echo SUCCESS >> status.txt || echo FAILzlib >> status.txt
./build-package.sh -a arm -I coreutils  && echo SUCCESS >> status.txt || echo FAILcoreutils >> status.txt
./build-package.sh -a arm -I dash  && echo SUCCESS >> status.txt || echo FAILdash >> status.txt
./build-package.sh -a arm -I diffutils  && echo SUCCESS >> status.txt || echo FAILdiffutils >> status.txt
./build-package.sh -a arm -I dos2unix  && echo SUCCESS >> status.txt || echo FAILdos2unix >> status.txt
./build-package.sh -a arm -I dpkg  && echo SUCCESS >> status.txt || echo FAILdpkg >> status.txt
./build-package.sh -a arm -I ed  && echo SUCCESS >> status.txt || echo FAILed >> status.txt
./build-package.sh -a arm -I ffmpeg  && echo SUCCESS >> status.txt || echo FAILffmpeg >> status.txt
./build-package.sh -a arm -I figlet  && echo SUCCESS >> status.txt || echo FAILfiglet >> status.txt
./build-package.sh -a arm -I findutils  && echo SUCCESS >> status.txt || echo FAILfindutils >> status.txt
./build-package.sh -a arm -I fontconfig  && echo SUCCESS >> status.txt || echo FAILfontconfig >> status.txt
./build-package.sh -a arm -I freetype  && echo SUCCESS >> status.txt || echo FAILfreetype >> status.txt
./build-package.sh -a arm -I fribidi  && echo SUCCESS >> status.txt || echo FAILfribidi >> status.txt
./build-package.sh -a arm -I gawk  && echo SUCCESS >> status.txt || echo FAILgawk >> status.txt
./build-package.sh -a arm -I gdbm  && echo SUCCESS >> status.txt || echo FAILgdbm >> status.txt
./build-package.sh -a arm -I git  && echo SUCCESS >> status.txt || echo FAILgit >> status.txt
./build-package.sh -a arm -I glib  && echo SUCCESS >> status.txt || echo FAILglib >> status.txt
./build-package.sh -a arm -I grep  && echo SUCCESS >> status.txt || echo FAILgrep >> status.txt
./build-package.sh -a arm -I gzip  && echo SUCCESS >> status.txt || echo FAILgzip >> status.txt
./build-package.sh -a arm -I harfbuzz  && echo SUCCESS >> status.txt || echo FAILharfbuzz >> status.txt
./build-package.sh -a arm -I inetutils  && echo SUCCESS >> status.txt || echo FAILinetutils >> status.txt
./build-package.sh -a arm -I json-c  && echo SUCCESS >> status.txt || echo FAILjson >> status.txt
./build-package.sh -a arm -I krb5  && echo SUCCESS >> status.txt || echo FAILkrb5 >> status.txt
./build-package.sh -a arm -I ldns  && echo SUCCESS >> status.txt || echo FAILldns >> status.txt
./build-package.sh -a arm -I less  && echo SUCCESS >> status.txt || echo FAILless >> status.txt
./build-package.sh -a arm -I libandroid-glob  && echo SUCCESS >> status.txt || echo FAILlibandroid-glob >> status.txt
./build-package.sh -a arm -I libandroid-support  && echo SUCCESS >> status.txt || echo FAILlibandroid-support >> status.txt
./build-package.sh -a arm -I libass  && echo SUCCESS >> status.txt || echo FAILlibass >> status.txt
./build-package.sh -a arm -I libc++  && echo SUCCESS >> status.txt || echo FAILlibc++ >> status.txt
./build-package.sh -a arm -I libcap  && echo SUCCESS >> status.txt || echo FAILlibcap >> status.txt
./build-package.sh -a arm -I libcrypt  && echo SUCCESS >> status.txt || echo FAILlibcrypt >> status.txt
./build-package.sh -a arm -I libdb  && echo SUCCESS >> status.txt || echo FAILlibdb >> status.txt
./build-package.sh -a arm -I libedit  && echo SUCCESS >> status.txt || echo FAILlibedit >> status.txt
./build-package.sh -a arm -I libffi  && echo SUCCESS >> status.txt || echo FAILlibffi >> status.txt
./build-package.sh -a arm -I libfuse  && echo SUCCESS >> status.txt || echo FAILlibfuse >> status.txt
./build-package.sh -a arm -I libgmp  && echo SUCCESS >> status.txt || echo FAILlibgmp >> status.txt
./build-package.sh -a arm -I libgnutls  && echo SUCCESS >> status.txt || echo FAILlibgnutls >> status.txt
./build-package.sh -a arm -I libgpg-error  && echo SUCCESS >> status.txt || echo FAILlibgpg-error >> status.txt
./build-package.sh -a arm -I libgraphite  && echo SUCCESS >> status.txt || echo FAILlibgraphite >> status.txt
./build-package.sh -a arm -I libiconv  && echo SUCCESS >> status.txt || echo FAILlibiconv >> status.txt
./build-package.sh -a arm -I libicu  && echo SUCCESS >> status.txt || echo FAILlibicu >> status.txt
./build-package.sh -a arm -I libidn2  && echo SUCCESS >> status.txt || echo FAILlibidn2 >> status.txt
./build-package.sh -a arm -I libjpeg-turbo  && echo SUCCESS >> status.txt || echo FAILlibjpeg-turbo >> status.txt
./build-package.sh -a arm -I liblzo  && echo SUCCESS >> status.txt || echo FAILliblzo >> status.txt
./build-package.sh -a arm -I libmosquitto  && echo SUCCESS >> status.txt || echo FAILlibmosquitto >> status.txt
./build-package.sh -a arm -I libmp3lame  && echo SUCCESS >> status.txt || echo FAILlibmp3lame >> status.txt
./build-package.sh -a arm -I libmpfr  && echo SUCCESS >> status.txt || echo FAILlibmpfr >> status.txt
./build-package.sh -a arm -I libnettle  && echo SUCCESS >> status.txt || echo FAILlibnettle >> status.txt
./build-package.sh -a arm -I libnghttp2  && echo SUCCESS >> status.txt || echo FAILlibnghttp2 >> status.txt
./build-package.sh -a arm -I libogg  && echo SUCCESS >> status.txt || echo FAILlibogg >> status.txt
./build-package.sh -a arm -I libopus  && echo SUCCESS >> status.txt || echo FAILlibopus >> status.txt
./build-package.sh -a arm -I libpng  && echo SUCCESS >> status.txt || echo FAILlibpng >> status.txt
./build-package.sh -a arm -I libpsl  && echo SUCCESS >> status.txt || echo FAILlibpsl >> status.txt
./build-package.sh -a arm -I libsigsegv  && echo SUCCESS >> status.txt || echo FAILlibsigsegv >> status.txt
./build-package.sh -a arm -I libsodium  && echo SUCCESS >> status.txt || echo FAILlibsodium >> status.txt
./build-package.sh -a arm -I libsoxr  && echo SUCCESS >> status.txt || echo FAILlibsoxr >> status.txt
./build-package.sh -a arm -I libsqlite  && echo SUCCESS >> status.txt || echo FAILlibsqlite >> status.txt
./build-package.sh -a arm -I libunistring  && echo SUCCESS >> status.txt || echo FAILlibunistring >> status.txt
./build-package.sh -a arm -I libuuid  && echo SUCCESS >> status.txt || echo FAILlibuuid >> status.txt
./build-package.sh -a arm -I libuv  && echo SUCCESS >> status.txt || echo FAILlibuv >> status.txt
./build-package.sh -a arm -I libvorbis  && echo SUCCESS >> status.txt || echo FAILlibvorbis >> status.txt
./build-package.sh -a arm -I libvpx  && echo SUCCESS >> status.txt || echo FAILlibvpx >> status.txt
./build-package.sh -a arm -I libwebsockets  && echo SUCCESS >> status.txt || echo FAILlibwebsockets >> status.txt
./build-package.sh -a arm -I libx264  && echo SUCCESS >> status.txt || echo FAILlibx264 >> status.txt
./build-package.sh -a arm -I libx265  && echo SUCCESS >> status.txt || echo FAILlibx265 >> status.txt
./build-package.sh -a arm -I libxml2  && echo SUCCESS >> status.txt || echo FAILlibxml2 >> status.txt
./build-package.sh -a arm -I libxslt  && echo SUCCESS >> status.txt || echo FAILlibxslt >> status.txt
./build-package.sh -a arm -I libzmq  && echo SUCCESS >> status.txt || echo FAILlibzmq >> status.txt
./build-package.sh -a arm -I m4  && echo SUCCESS >> status.txt || echo FAILm4 >> status.txt
./build-package.sh -a arm -I make  && echo SUCCESS >> status.txt || echo FAILmake >> status.txt
./build-package.sh -a arm -I nano  && echo SUCCESS >> status.txt || echo FAILnano >> status.txt
./build-package.sh -a arm -I ncurses  && echo SUCCESS >> status.txt || echo FAILncurses >> status.txt
./build-package.sh -a arm -I ndk-sysroot  && echo SUCCESS >> status.txt || echo FAILndk-sysroot >> status.txt
./build-package.sh -a arm -I net-tools  && echo SUCCESS >> status.txt || echo FAILnet-tools >> status.txt
./build-package.sh -a arm -I nodejs-lts  && echo SUCCESS >> status.txt || echo FAILnodejs-lts >> status.txt
./build-package.sh -a arm -I openssh  && echo SUCCESS >> status.txt || echo FAILopenssh >> status.txt
./build-package.sh -a arm -I openssl  && echo SUCCESS >> status.txt || echo FAILopenssl >> status.txt
./build-package.sh -a arm -I patch  && echo SUCCESS >> status.txt || echo FAILpatch >> status.txt
./build-package.sh -a arm -I pcre  && echo SUCCESS >> status.txt || echo FAILpcre >> status.txt
./build-package.sh -a arm -I pcre2  && echo SUCCESS >> status.txt || echo FAILpcre >> status.txt
./build-package.sh -a arm -I perl  && echo SUCCESS >> status.txt || echo FAILperl >> status.txt
./build-package.sh -a arm -I pkg-config  && echo SUCCESS >> status.txt || echo FAILpkg-config >> status.txt
./build-package.sh -a arm -I procps  && echo SUCCESS >> status.txt || echo FAILprocps >> status.txt
./build-package.sh -a arm -I psmisc  && echo SUCCESS >> status.txt || echo FAILpsmisc >> status.txt
./build-package.sh -a arm -I python  && echo SUCCESS >> status.txt || echo FAILpython >> status.txt
./build-package.sh -a arm -I rclone  && echo SUCCESS >> status.txt || echo FAILrclone >> status.txt
./build-package.sh -a arm -I readline  && echo SUCCESS >> status.txt || echo FAILreadline >> status.txt
./build-package.sh -a arm -I sed  && echo SUCCESS >> status.txt || echo FAILsed >> status.txt
./build-package.sh -a arm -I tar  && echo SUCCESS >> status.txt || echo FAILtar >> status.txt
./build-package.sh -a arm -I termux-am  && echo SUCCESS >> status.txt || echo FAILtermux-am >> status.txt
./build-package.sh -a arm -I termux-api  && echo SUCCESS >> status.txt || echo FAILtermux-api >> status.txt
./build-package.sh -a arm -I termux-auth  && echo SUCCESS >> status.txt || echo FAILtermux-auth >> status.txt
./build-package.sh -a arm -I termux-exec  && echo SUCCESS >> status.txt || echo FAILtermux-exec >> status.txt
./build-package.sh -a arm -I termux-licenses  && echo SUCCESS >> status.txt || echo FAILtermux-licenses >> status.txt
./build-package.sh -a arm -I termux-tools  && echo SUCCESS >> status.txt || echo FAILtermux-tools >> status.txt
./build-package.sh -a arm -I ttyd  && echo SUCCESS >> status.txt || echo FAILttyd >> status.txt
./build-package.sh -a arm -I unzip  && echo SUCCESS >> status.txt || echo FAILunzip >> status.txt
./build-package.sh -a arm -I xvidcore  && echo SUCCESS >> status.txt || echo FAILxvidcore >> status.txt
./build-package.sh -a arm -I util-linux  && echo SUCCESS >> status.txt || echo FAILutil-linux >> status.txt
./build-package.sh -a arm -I leptonica && echo SUCCESS >> status.txt || echo FAILleptonica >> status.txt
./build-package.sh -a arm -I sox && echo SUCCESS >> status.txt || echo FAILsox >> status.txt
./build-package.sh -a arm -I postgresql && echo SUCCESS >> status.txt || echo FAILpostgresql >> status.txt
