./build-package.sh -a arm -I leptonica
./build-package.sh -a arm -I libwebp
./build-package.sh -a arm -I sox

./build-package.sh -a arm -I libacl
./build-package.sh -a arm -I libssh
./build-package.sh -a arm -I libssh2
./build-package.sh -a arm -I postgresql
./build-package.sh -a arm -I libdav1d
./build-package.sh -a arm -I libvidstab
./build-package.sh -a arm -I ttf-dejavu
./build-package.sh -a arm -I libgcrypt
./build-package.sh -a arm -I libassuan
./build-package.sh -a arm -I liblz4
./build-package.sh -a arm -I apt
./build-package.sh -a arm -i attr
./build-package.sh -a arm -i autoconf
./build-package.sh -a arm -i bash
./build-package.sh -a arm -i binutils
./build-package.sh -a arm -i busybox
./build-package.sh -a arm -i ca-certificates
./build-package.sh -a arm -i command-not-found
./build-package.sh -a arm -i libllvm
./build-package.sh -a arm -i libbz2
./build-package.sh -a arm -i libcurl
./build-package.sh -a arm -i gnupg
./build-package.sh -a arm -i libmosquitto
./build-package.sh -a arm -i liblzma
./build-package.sh -a arm -i zlib
./build-package.sh -a arm -i coreutils
./build-package.sh -a arm -i dash
./build-package.sh -a arm -i diffutils
./build-package.sh -a arm -i dos2unixlibass
./build-package.sh -a arm -i dpkg
./build-package.sh -a arm -i ed
./build-package.sh -a arm -i ffmpeg
./build-package.sh -a arm -i findutils
./build-package.sh -a arm -i fontconfig
./build-package.sh -a arm -i freetype
./build-package.sh -a arm -i fribidi
./build-package.sh -a arm -i gawk
./build-package.sh -a arm -i gdbm
./build-package.sh -a arm -i git
./build-package.sh -a arm -i glib
./build-package.sh -a arm -i grep
./build-package.sh -a arm -i gzip
./build-package.sh -a arm -i harfbuzz
./build-package.sh -a arm -i inetutils
./build-package.sh -a arm -i json-c
./build-package.sh -a arm -i krb5
./build-package.sh -a arm -i ldns
./build-package.sh -a arm -i less
./build-package.sh -a arm -i libandroid-glob
./build-package.sh -a arm -i libandroid-support
./build-package.sh -a arm -i libass
./build-package.sh -a arm -i libc++
./build-package.sh -a arm -i libcap
./build-package.sh -a arm -i libcrypt
./build-package.sh -a arm -i libdb
./build-package.sh -a arm -i libedit
./build-package.sh -a arm -i libffi
./build-package.sh -a arm -i libfuse
./build-package.sh -a arm -i libgmp
./build-package.sh -a arm -i libgnutls
./build-package.sh -a arm -i libgpg-error
./build-package.sh -a arm -i libgraphite
./build-package.sh -a arm -i libiconv
./build-package.sh -a arm -i libicu
./build-package.sh -a arm -i libidn2
./build-package.sh -a arm -i libjpeg-turbo
./build-package.sh -a arm -i liblzo
./build-package.sh -a arm -i libmp3lame
./build-package.sh -a arm -i libmpfr
./build-package.sh -a arm -i libnettle
./build-package.sh -a arm -i libnghttp2
./build-package.sh -a arm -i libogg
./build-package.sh -a arm -i libopus
./build-package.sh -a arm -i libpng
./build-package.sh -a arm -i libpsl
./build-package.sh -a arm -i libsigsegv
./build-package.sh -a arm -i libsodium
./build-package.sh -a arm -i libsoxr
./build-package.sh -a arm -i libsqlite
./build-package.sh -a arm -i libunistring
./build-package.sh -a arm -i libuuid
./build-package.sh -a arm -i libuv
./build-package.sh -a arm -i libvorbis
./build-package.sh -a arm -i libvpx
./build-package.sh -a arm -i libwebsockets
./build-package.sh -a arm -i libx264
./build-package.sh -a arm -i libx265
./build-package.sh -a arm -i libxml2
./build-package.sh -a arm -i libxslt
./build-package.sh -a arm -i libzmq
./build-package.sh -a arm -i m4
./build-package.sh -a arm -i make
./build-package.sh -a arm -i ncurses
./build-package.sh -a arm -i ncurses-ui-libs
./build-package.sh -a arm -i ndk-sysroot
./build-package.sh -a arm -i net-tools
./build-package.sh -a arm -i openssh
./build-package.sh -a arm -i openssl
./build-package.sh -a arm -i patch
./build-package.sh -a arm -i pcre
./build-package.sh -a arm -i pcre2
./build-package.sh -a arm -i perl
./build-package.sh -a arm -i pkg-config
./build-package.sh -a arm -i procps
./build-package.sh -a arm -i psmisc
./build-package.sh -a arm -i python
./build-package.sh -a arm -i rclone
./build-package.sh -a arm -i readline
./build-package.sh -a arm -i sed
./build-package.sh -a arm -i tar
./build-package.sh -a arm -i termux-am
./build-package.sh -a arm -i termux-api
./build-package.sh -a arm -i termux-auth
./build-package.sh -a arm -i termux-exec
./build-package.sh -a arm -i termux-licenses
./build-package.sh -a arm -i termux-tools
./build-package.sh -a arm -i ttyd
./build-package.sh -a arm -i unzip
./build-package.sh -a arm -i util-linux
./build-package.sh -a arm -i xvidcore
./build-package.sh -a arm -I c-ares
./build-package.sh -a arm -i nodejs-lts
